# Generated by Django 4.0.3 on 2022-04-06 10:19

import company.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': ('Департамент',), 'verbose_name_plural': 'Департамент'},
        ),
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='company.employee', validators=[company.validators.validate_director], verbose_name='Директор'),
        ),
    ]
